config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :users, only: [:new, :create]
  resources :short_urls
  post '/token', to: 'users#token'
  get '/unauthenticated', to: 'pages#unauthenticated'
  get '/unauthorized', to: 'pages#unauthorized'
  get 'analytics/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/base_api.rb
class BaseApi < ActiveResource::Base
  self.site = 'http://localhost:3000/api/v1'
  self.headers['Content-Type'] = 'application/json'

  cattr_accessor :static_headers
  self.static_headers = headers

  cattr_accessor :token

  def self.headers
    new_headers = static_headers.clone
    new_headers["Authorization"] = "Token token=#{token}"
    new_headers
  end
end

app/models/short_url.rb
class ShortUrl < BaseApi
  schema do
    string 'original', 'converted'
  end
end

app/models/user.rb
class User < BaseApi
  schema do
    string 'name', 'password', 'password_confirmation'
  end
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  before_action :set_token

  def index
    @short_urls = ShortUrl.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from ActiveResource::UnauthorizedAccess, with: :unauthenticated
  rescue_from ActiveResource::ForbiddenAccess, with: :unauthorized

  private
  def unauthenticated
    redirect_to unauthenticated_path
  end

  def unauthorized
    redirect_to unauthorized_path
  end

  def set_token
    BaseApi.token = session[:token]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def unauthorized
  end

  def unauthenticated
  end
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController
  before_action :set_short_url, only: [:show, :edit, :update, :destroy]
  before_action :set_token

  # GET /short_urls
  def index
    @short_urls = ShortUrl.all
  end

  # GET /short_urls/1
  def show
  end

  # GET /short_urls/new
  def new
    @short_url = ShortUrl.new
  end

  # POST /short_urls
  def create
    @short_url = ShortUrl.new(short_url_params)

    if @short_url.save
      redirect_to @short_url, notice: 'Short url was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /short_urls/1
  def update
    if @short_url.update(short_url_params)
      redirect_to @short_url, notice: 'Short url was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /short_urls/1
  def destroy
    @short_url.destroy
    redirect_to short_urls_url, notice: 'Short url was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_short_url
      @short_url = ShortUrl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def short_url_params
      params.require(:short_url).permit(:original, :converted).to_h
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def token
    session[:token] = params[:user][:token]
    set_token
    redirect_to short_urls_path
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:token] = @user.api_key
      redirect_to short_urls_path
    else
      render :new
    end

  end

  private
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation).to_h
    end
end

app/helpers/analytics_helper.rb
module AnalyticsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/short_urls_helper.rb
module ShortUrlsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/analytics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Analytics</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Original</th>
      <th>Converted</th>
      <th>Creation date</th>
      <th>Times used</th>
    </tr>
  </thead>

  <tbody>
    <% @short_urls.each do |short_url| %>
      <tr>
        <td><%= short_url.original %></td>
        <td><%= link_to short_url.converted, short_url.converted %></td>
        <td><%= time_ago_in_words(short_url.created_at) + ' ago' %></td>
        <td><%= short_url.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BloggerConsumer" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <nav class="navbar navbar-dark bg-inverse">
      <div class="container">
        <a class="navbar-brand" href="#">Wizeline</a>
        <ul class="nav navbar-nav">
          <li class="nav-item active">
            <%= link_to 'URLS', short_urls_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'New User', new_user_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Analytics', analytics_index_path, class: 'nav-link' %>
          </li>
        </ul>
        <%= form_tag(token_path, remote: true, class: 'form-inline float-xs-right col-sm-4')do %>
          <%= text_field :user, :token, placeholder: 'Token',
            class: 'form-control', style: 'width: 77%', value: session[:token] %>
          <button class="btn btn-outline-success" type="submit">Save</button>
        <% end %>
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Wizeline 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/unauthenticated.html.erb
<h1>Token inválido</h1>

app/views/pages/unauthorized.html.erb
<h1>No tienes permisos para realizar esa acción</h1>

app/views/short_urls/_form.html.erb
<%= simple_form_for(@short_url) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :original %>
    <%= f.input :converted %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/short_urls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Short Urls</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Original</th>
      <th>Converted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @short_urls.each do |short_url| %>
      <tr>
        <td><%= short_url.original %></td>
        <td><%= link_to short_url.converted, short_url.converted %></td>
        <td><%= link_to 'Show', short_url %></td>
        <td><%= link_to 'Edit', edit_short_url_path(short_url) %></td>
        <td><%= link_to 'Destroy', short_url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Short Url', new_short_url_path %>

app/views/short_urls/new.html.erb
<h1>New Short Url</h1>

<%= render 'form', short_url: @short_url %>

<%= link_to 'Back', short_urls_path %>

app/views/short_urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Original:</strong>
  <%= @short_url.original %>
</p>

<p>
  <strong>Converted:</strong>
  <%= link_to @short_url.converted, @short_url.converted %>
</p>

<p>
  <strong>Created:</strong>
  <%= time_ago_in_words(@short_url.created_at) + ' ago' %>
</p>

<p>
  <strong>Times used:</strong>
  <%= @short_url.count %>
</p>

<%= link_to 'Edit', edit_short_url_path(@short_url) %> |
<%= link_to 'Back', short_urls_path %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>